# Generated by Django 3.2.7 on 2021-09-15 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(default='mensagem')),
                ('tratado', models.BooleanField(default=False)),
                ('data_contact', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='bathroom',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='nº wc'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='bed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='nº quartos'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='construction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Área de Construção'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_post',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='garage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='nº garagem'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem_post',
            field=models.ImageField(default=1, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem De Perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='implantation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Área de Implantação'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='lote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Área de Lote'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='parish',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Freguesia'),
        ),
        migrations.CreateModel(
            name='GaleriaPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projeto')),
            ],
        ),
    ]
