# Generated by Django 3.2.7 on 2021-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210915_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Foto')),
                ('job', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissão')),
                ('testimony', models.CharField(max_length=300, verbose_name='testemunho')),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem_post',
            field=models.ImageField(default=1, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem De Perfil'),
            preserve_default=False,
        ),
    ]
