# Generated by Django 3.2.7 on 2021-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_testemunho_data_testemunho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaphotos',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='testemunho',
            name='testimony',
            field=models.TextField(verbose_name='testemunho'),
        ),
    ]
